"""empty message

Revision ID: 159f8670da78
Revises: 4b570c82b945
Create Date: 2020-01-29 23:30:35.498000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159f8670da78'
down_revision = '4b570c82b945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('queue_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'queue_name')
    # ### end Alembic commands ###
